module.exports = {
  purge: {
    content: [
      "./views/**/*.php",
      "./resources/**/*.js",
      "./resources/**/*.jsx",
    ],
  },
  theme: {
    fontFamily: {
      sans: ["Inter"],
    },
    extend: {
      colors: {
        "theme-dark": "#4fabfe",
        "theme-darkest": "#12283a",
      },
    },
    variants: {
      alignContent: ["responsive"],
      alignItems: ["responsive"],
      alignSelf: ["responsive"],
      appearance: ["responsive"],
      backgroundAttachment: ["responsive"],
      backgroundColor: ["responsive", "hover", "focus"],
      backgroundPosition: ["responsive"],
      backgroundRepeat: ["responsive"],
      backgroundSize: ["responsive"],
      borderCollapse: ["responsive"],
      borderColor: ["responsive", "hover", "focus"],
      borderRadius: ["responsive"],
      borderStyle: ["responsive"],
      borderWidth: ["responsive"],
      boxShadow: ["responsive", "hover", "focus"],
      cursor: ["responsive"],
      display: ["responsive"],
      fill: ["responsive"],
      flex: ["responsive"],
      flexDirection: ["responsive"],
      flexGrow: ["responsive"],
      flexShrink: ["responsive"],
      flexWrap: ["responsive"],
      float: ["responsive"],
      fontFamily: ["responsive"],
      fontSize: ["responsive"],
      fontSmoothing: ["responsive"],
      fontStyle: ["responsive"],
      fontWeight: ["responsive", "hover", "focus"],
      height: ["responsive"],
      inset: ["responsive"],
      justifyContent: ["responsive"],
      letterSpacing: ["responsive"],
      lineHeight: ["responsive"],
      listStylePosition: ["responsive"],
      listStyleType: ["responsive"],
      margin: ["responsive"],
      maxHeight: ["responsive"],
      maxWidth: ["responsive"],
      minHeight: ["responsive"],
      minWidth: ["responsive"],
      objectFit: ["responsive"],
      objectPosition: ["responsive"],
      opacity: ["responsive"],
      order: ["responsive"],
      outline: ["responsive", "focus"],
      overflow: ["responsive"],
      padding: ["responsive"],
      pointerEvents: ["responsive"],
      position: ["responsive"],
      resize: ["responsive"],
      stroke: ["responsive"],
      tableLayout: ["responsive"],
      textAlign: ["responsive"],
      textColor: ["responsive", "hover", "focus"],
      textDecoration: ["responsive", "hover", "focus"],
      textTransform: ["responsive"],
      userSelect: ["responsive"],
      verticalAlign: ["responsive"],
      visibility: ["responsive"],
      whitespace: ["responsive"],
      width: ["responsive"],
      wordBreak: ["responsive"],
      zIndex: ["responsive"],
    },
  },
};
